MonoProjekt.MVC/Models/ErrorViewModel.cs
namespace MonoProjekt.MVC.Models
{
    public class ErrorViewModel
    {
        #region Properties

        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        #endregion Properties
    }
}

MonoProjekt.MVC/Models/VehicleMakeRestModel.cs
namespace MonoProjekt.MVC.Models
{
    public class VehicleMakeRestModel
    {
        #region Properties

        public string Abrv { get; set; }
        public Guid Id { get; set; }
        public string Name { get; set; }

        #endregion Properties
    }
}

MonoProjekt.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MonoProjekt.MVC.Models;
using System.Diagnostics;

namespace MonoProjekt.MVC.Controllers
{
    public class HomeController : Controller
    {
        #region Fields

        private readonly ILogger<HomeController> _logger;

        #endregion Fields

        #region Constructors

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        #endregion Constructors

        #region Methods

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        #endregion Methods
    }
}

MonoProjekt.MVC/Controllers/VehicleMakeController.cs
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MonoProjekt.MVC.Models;
using MonoProjekt.Service.DAL;
using MonoProjekt.Service.Models;
using MonoProjekt.Service.Service.Common;

namespace MonoProjekt.MVC.Controllers
{
    public class VehicleMakeController : Controller
    {
        #region Constructors

        public VehicleMakeController(IVehicleMakeService vehicleMakeService, IMapper mapper)
        {
            VehicleMakeService = vehicleMakeService;
            Mapper = mapper;
        }

        #endregion Constructors

        #region Properties

        public IMapper Mapper { get; set; }
        public IVehicleMakeService VehicleMakeService { get; set; }

        #endregion Properties

        #region Methods

        public IActionResult Create()
        {
            return View();
        }

        [HttpDelete("{id}")]
        public async Task<ActionResult> DeleteVehicleMaker(Guid id)
        {
            var vehicleMaker = await VehicleMakeService.FindVehicleMakerAsync(id);
            if (vehicleMaker == null)
            {
                return NotFound();
            }
            await VehicleMakeService.DeleteVehicleMakerAsync(vehicleMaker.Id);
            return NoContent();
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<VehicleMake>> FindVehicleMaker(Guid id)
        {
            return await VehicleMakeService.FindVehicleMakerAsync(id);
        }

        public IActionResult Index()
        {
            var result = VehicleMakeService.GetAllVehicleMakers();
            if (result != null)
            {
                var restModel = Mapper.Map<List<VehicleMakeRestModel>>(result);
                return View(restModel);
            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<ActionResult<VehicleMake>> PostVehicleMaker([FromBody] VehicleMake vehicleMake)
        {
            var newVehicleMaker = await VehicleMakeService.InsertVehicleMakerAsync(vehicleMake);
            return Ok(newVehicleMaker);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpPut]
        public async Task<ActionResult> PutVehicleMaker(Guid id, [FromBody] VehicleMake vehicleMake)
        {
            if (id != vehicleMake.Id)
            {
                return BadRequest();
            }

            await VehicleMakeService.UpdateVehicleMakerAsync(vehicleMake);
            return Ok();
        }

        #endregion Methods
    }
}

MonoProjekt.MVC/Controllers/VehicleModelController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MonoProjekt.Service.Models;
using MonoProjekt.Service.Service.Common;

namespace MonoProjekt.MVC.Controllers
{
    public class VehicleModelController : Controller
    {
        #region Constructors

        public VehicleModelController(IVehicleModelService vehicleModelService, IMapper mapper)
        {
            VehicleModelService = vehicleModelService;
            Mapper = mapper;
        }

        #endregion Constructors

        #region Properties

        public IMapper Mapper { get; set; }
        public IVehicleModelService VehicleModelService { get; set; }

        #endregion Properties

        #region Methods

        [HttpDelete("{id}")]
        public async Task<ActionResult> DeleteVehicleModel(Guid id)
        {
            var vehicleModel = await VehicleModelService.FindVehicleModelAsync(id);
            if (vehicleModel == null)
            {
                return NotFound();
            }
            await VehicleModelService.DeleteVehicleModelAsync(vehicleModel.Id);
            return NoContent();
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<VehicleModel>> FindVehicleModel(Guid id)
        {
            return await VehicleModelService.FindVehicleModelAsync(id);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult<VehicleModel>> PostVehicleModel([FromBody] VehicleModel vehicleModel)
        {
            return await VehicleModelService.InsertVehicleModelAsync(vehicleModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpPut]
        public async Task<ActionResult> PutVehicleModel(Guid id, [FromBody] VehicleModel vehicleModel)
        {
            if (id != vehicleModel.Id)
            {
                return BadRequest();
            }

            await VehicleModelService.UpdateVehicleModelAsync(vehicleModel);
            return Ok();
        }

        #endregion Methods
    }
}

MonoProjekt.MVC/Views/Home/Index.cshtml
@using MonoProjekt.MVC.Models

@model IEnumerable<VehicleMakeRestModel> 
@{
    ViewData["Title"] = "Index";
}

<h1>Index VehicleMake</h1>


<table class="table table-bordered table-striped" style="width:100%" >
	<thead>
		<tr>
			<th>
				VehicleMake Name
			</th>
			<th>
				Guid Id
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach(var obj in Model)
		{
			<tr>
				<td width="50%">
					@obj?.Name
				</td>
				<td width="30%">
					@obj?.Id
				</td>
			</tr>
		}
	</tbody>
</table>

MonoProjekt.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonoProjekt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MonoProjekt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MonoProjekt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleModel" asp-action="Index">VehicleModel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleMake" asp-action="Index">VehicleMake</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MonoProjekt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MonoProjekt.MVC/Views/VehicleMake/Create.cshtml
@using MonoProjekt.Service.DAL

@model VehicleMakeEntity

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Category</h2>
			<hr />

		</div>
	</div>
</form>